<a href="https://colab.research.google.com/github/shannonshih/Tibame_GAD245-Practice-HW_0113/blob/main/Practice01_0113.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import urllib.request as req
import bs4 as bs
# Step 0.
import pandas as pd
url = "https://tabelog.com/tw/tokyo/rstLst/1/?SrtT=rt"
response = req.urlopen(url)
html = bs.BeautifulSoup(response)

# Step 1. 準備一個空的list
table = []

# find_all: 形態是個類似list的
page = 1
while True:
    print("頁數:", page)
    url = "https://tabelog.com/tw/tokyo/rstLst/{}/?SrtT=rt".format(page)
    page = page + 1
    response = req.urlopen(url)
    html = bs.BeautifulSoup(response)

    r_list = html.find_all("div", {"class":"list-rst__body"})
    if len(r_list) == 0:
        break

    for r in r_list:
        en_name = r.find("a", {"class":"list-rst__rst-name-target"})
        en_name_href = en_name["href"]
        en_name_text = en_name.text
        area = r.find("div", {"class":"list-rst__area-genre"})
        area_text = area.text.strip()
        intro = r.find("p", {"class":"list-rst__pr-title"})
        if intro == None:
            intro_text = "無"
        else:
            intro_text = intro.text.strip()
        rating = r.find("span", {"class":"c-rating__val"})
        rating_text = rating.text
        prices = r.find_all("span", {"class":"c-rating-v3__val"})
        dinner_price = prices[0].text
        lunch_price = prices[1].text
        holiday = r.find("span", {"class":"list-rst__holiday-text"})
        holiday_text = holiday.text

        print(rating_text)
        print(en_name_text)
        print(en_name_href)
        print(area_text)
        print(intro_text)
        print(holiday_text)
        print("晚間價錢:", dinner_price, "午間價錢:", lunch_price)
        print("-" * 30)

        # Step2. 每一筆資料就是一個字典
        data = {
            "name(en)": en_name_text,
            "url": en_name_href,
            "area": area_text,
            "intro": intro_text,
            "rating": rating_text,
            "holiday": holiday_text,
        }
        table.append(data)

# Step3. 轉成DataFrame儲存
df = pd.DataFrame(table,
          columns=["name(en)", "url", "area", "intro", "rating", "holiday"])
df.to_csv("tabelog.csv", encoding="utf-8")

串流輸出內容已截斷至最後 5000 行。
3.78
SIROTAE
https://tabelog.com/tw/tokyo/A1308/A130801/13002850/
赤坂見附車站 / 蛋糕, 咖啡店, 喫茶店
無
星期一、星期日
晚間價錢: - 午間價錢: JPY 1,000～JPY 1,999
------------------------------
頁數: 30
3.78
Naniwaya Sohonten
https://tabelog.com/tw/tokyo/A1307/A130702/13002775/
麻布十番車站 / 日式甜點店, 鯛魚燒・大判燒, 炒麵
無
星期二、星期三
晚間價錢: - 午間價錢: ～JPY 999
------------------------------
3.78
Niboshi Tsukemen Miyamoto
https://tabelog.com/tw/tokyo/A1315/A131503/13180862/
蒲田車站 / 沾麵, 拉麵
[從蒲田車站步行4分鐘]獨一無二的拉麵！ ！
星期日
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Tsukesoba Kanda Katsumoto
https://tabelog.com/tw/tokyo/A1310/A131003/13192433/
神保町車站 / 沾麵, 拉麵
無
星期日
晚間價錢: - 午間價錢: ～JPY 999
------------------------------
3.78
Mentokoro Ginzasa
https://tabelog.com/tw/tokyo/A1301/A130103/13119563/
築地市場車站 / 拉麵, 沾麵
無
星期日、節假日
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Ramen Kai
https://tabelog.com/tw/tokyo/A1311/A131103/13191776/
藏前車站 / 拉麵, 沾麵
無
-
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Yanagiya
https://tabelog.com/tw/tokyo/A1302/A130204/13003065/
人形町車站 / 鯛魚燒・大判燒, 意式冰淇淋/冰淇淋
無
星期一、星期日
晚間價錢: - 午間價錢: ～JPY 999
------------------------------
3.78
Takesue Tokyo Premium
https://tabelog.com/tw/tokyo/A1312/A131203/13167920/
押上車站 / 拉麵, 沾麵
無
星期二
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Rodin
https://tabelog.com/tw/tokyo/A1302/A130203/13048485/
寶町車站 / 咖喱, 印度咖哩
無
-
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
La Boutique de Joël Robuchon Marunochi Burikkusukuea Ten
https://tabelog.com/tw/tokyo/A1302/A130201/13096409/
二重橋前車站 / 麵包, 蛋糕, 咖啡店
無
-
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Kuromatsu Honpo Sogetsu
https://tabelog.com/tw/tokyo/A1323/A132304/13003793/
東十條車站 / 日式點心, 銅鑼燒
無
星期二
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.78
Spice Ramen Manriki Nishi Kasai Ten
https://tabelog.com/tw/tokyo/A1313/A131305/13168253/
西葛西車站 / 拉麵, 沾麵
無
星期三
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.78
Yoshida Curry
https://tabelog.com/tw/tokyo/A1319/A131906/13132405/
荻窪車站 / 咖喱, 印度咖哩
無
星期三、星期四、星期日、節假日
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Hatsune
https://tabelog.com/tw/tokyo/A1319/A131907/13000717/
西荻窪車站 / 拉麵
無
星期一、星期日
晚間價錢: - 午間價錢: ～JPY 999
------------------------------
3.78
Waguri Ya Yanaka Ten
https://tabelog.com/tw/tokyo/A1311/A131106/13130539/
千馱木車站 / 甜點, 咖啡店, 意式冰淇淋/冰淇淋
無
-
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Shina Soba Tantantei
https://tabelog.com/tw/tokyo/A1318/A131805/13000705/
濱田山車站 / 拉麵, 沾麵
無
-
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Mendokoro Kinari
https://tabelog.com/tw/tokyo/A1319/A131901/13221001/
東中野車站 / 拉麵, 沾麵
最精緻的非化學風格拉麵，閃耀著法國美食的精髓。
星期三
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.78
Niboshi Soba Ru.
https://tabelog.com/tw/tokyo/A1323/A132304/13175140/
十條車站 / 拉麵, 沾麵, 油麵/拌麵
無
星期二
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.78
Le Pan de Joel Robuchon Shibuya Hikarieshinkyuesuten
https://tabelog.com/tw/tokyo/A1303/A130301/13140263/
澀谷車站 / 麵包, 三明治, 西式甜點
無
-
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
The KARI
https://tabelog.com/tw/tokyo/A1301/A130103/13007129/
御成門車站 / 咖喱
無
星期六、星期日、節假日
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
pointage
https://tabelog.com/tw/tokyo/A1307/A130702/13004566/
麻布十番車站 / 麵包, 法式小酒館, 咖啡店
無
星期一、星期二
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
頁數: 31
3.78
Nata de Cristiano's
https://tabelog.com/tw/tokyo/A1318/A131810/13153384/
代代木公園車站 / 甜點, 麵包, 蛋糕
無
-
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.78
Wa kitchen Kanna
https://tabelog.com/tw/tokyo/A1317/A131706/13156812/
三軒茶屋車站 / 剉冰, 創作料理, 日式小酒館
無
星期三
晚間價錢: - 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Ramen Gantetsu
https://tabelog.com/tw/tokyo/A1305/A130504/13167439/
早稻田車站 / 拉麵
無
星期日
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
French Gashi Patissier Chocolatier Inamura Shozo
https://tabelog.com/tw/tokyo/A1311/A131105/13047298/
日暮里車站 / 蛋糕, 巧克力
無
星期一
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Machi no Parlor
https://tabelog.com/tw/tokyo/A1321/A132101/13126515/
小竹向原車站 / 麵包, 咖啡店, 三明治
無
星期二
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Chiba Ya
https://tabelog.com/tw/tokyo/A1311/A131102/13008691/
淺草車站 / 烤地瓜/拔丝地瓜, 日式點心, 甜點
無
星期二
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.78
Menya Suzuharu
https://tabelog.com/tw/tokyo/A1310/A131004/13250293/
本鄉三丁目車站 / 拉麵, 沾麵
無
星期日
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Hakodate Shio Ramen Goryokaku
https://tabelog.com/tw/tokyo/A1319/A131906/13154596/
荻窪車站 / 拉麵
無
星期一、星期二
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.78
Ramen Hazuki
https://tabelog.com/tw/tokyo/A1317/A131714/13008248/
雪谷大塚車站 / 拉麵, 沾麵
無
星期一、星期二
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Matsushimaya
https://tabelog.com/tw/tokyo/A1314/A131403/13007137/
泉岳寺車站 / 日式點心, 大福麻糬
無
星期日
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.78
Mizuho
https://tabelog.com/tw/tokyo/A1306/A130601/13001154/
明治神宮前車站 / 日式點心, 大福麻糬
無
-
晚間價錢: - 午間價錢: ～JPY 999
------------------------------
3.78
BOULANGERIE SEIJI ASAKURA
https://tabelog.com/tw/tokyo/A1316/A131603/13055881/
高輪台車站 / 麵包
無
星期六
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.78
Zuckerbäckerei Kayanuma
https://tabelog.com/tw/tokyo/A1308/A130802/13002756/
溜池山王車站 / 蛋糕, 西式甜點
無
星期一、星期日、節假日
晚間價錢: JPY 3,000～JPY 3,999 午間價錢: -
------------------------------
3.78
Nakasuyatai Nagahama Ramen Shodai Kenta Tokyo Koenji Honten
https://tabelog.com/tw/tokyo/A1319/A131904/13183596/
高圓寺車站 / 拉麵
無
星期一
晚間價錢: - 午間價錢: ～JPY 999
------------------------------
3.78
LA BOUTIQUE de Joel Rubchon Roppongi Hiruzu Ten
https://tabelog.com/tw/tokyo/A1307/A130701/13020237/
六本木車站 / 麵包, 蛋糕
無
-
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Tori Ki
https://tabelog.com/tw/tokyo/A1312/A131201/13026017/
錦糸町車站 / 烤雞肉串
用熟練的火候精心烤制而成的一串。層出不窮的雞肉懷石料理讓客人贊嘆不已。
星期日、節假日
晚間價錢: JPY 10,000～JPY 14,999 午間價錢: -
------------------------------
3.78
Usagiya Chuo Tori Ten
https://tabelog.com/tw/tokyo/A1302/A130202/13041161/
日本橋車站 / 日式點心, 銅鑼燒
無
星期日
晚間價錢: ～JPY 999 午間價錢: -
------------------------------
3.78
Okashi Dokoro Sasama
https://tabelog.com/tw/tokyo/A1310/A131003/13000627/
神保町車站 / 日式點心
無
星期日、節假日
晚間價錢: ～JPY 999 午間價錢: -
------------------------------
3.78
MAISON D'AHNI
https://tabelog.com/tw/tokyo/A1316/A131602/13183428/
白金高輪車站 / 蛋糕, 麵包
無
星期二
晚間價錢: - 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Pan Chimahar
https://tabelog.com/tw/tokyo/A1310/A131003/13026681/
神保町車站 / 咖喱, 湯咖哩
無
星期日、節假日
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
頁數: 32
3.78
HENDRIX CURRY BAR
https://tabelog.com/tw/tokyo/A1309/A130901/13007422/
國立競技場車站 / 咖喱, 餐飲酒館, 印度咖哩
無
星期日、節假日
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Indian Curry Kaama
https://tabelog.com/tw/tokyo/A1310/A131003/13000243/
神保町車站 / 印度咖哩, 咖喱
無
-
晚間價錢: - 午間價錢: ～JPY 999
------------------------------
3.78
L’AUTOMNE Akitsu Honten
https://tabelog.com/tw/tokyo/A1328/A132806/13005967/
新秋津車站 / 蛋糕, 馬卡龍, 西式甜點
無
星期三
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.78
Le Bourguignon
https://tabelog.com/tw/tokyo/A1307/A130701/13005328/
六本木車站 / 法式料理
在能感受到勃艮第氣息的可愛空間裡，品嘗充滿主廚感性閃耀的至福的一道菜。
星期三
晚間價錢: JPY 15,000～JPY 19,999 午間價錢: JPY 5,000～JPY 5,999
------------------------------
3.78
Ramen Kajiwara
https://tabelog.com/tw/tokyo/A1318/A131809/13275969/
千歲烏山車站 / 拉麵
無
星期一、星期二
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Unagi Tokito
https://tabelog.com/tw/tokyo/A1307/A130702/13224663/
麻布十番車站 / 鰻魚, 日本料理, 法式料理
世界第一鰻魚法式料理割烹調“重視借鑒過去、適應時代的新標準”
星期日
晚間價錢: JPY 15,000～JPY 19,999 午間價錢: JPY 10,000～JPY 14,999
------------------------------
3.78
bistrosimba
https://tabelog.com/tw/tokyo/A1313/A131301/13186713/
新富町車站 / 法式小酒館, 法式料理
無
-
晚間價錢: JPY 10,000～JPY 14,999 午間價錢: -
------------------------------
3.78
Ittou An
https://tabelog.com/tw/tokyo/A1323/A132304/13143622/
東十條車站 / 蕎麥麵, 日本酒
無
星期一、星期日
晚間價錢: - 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.78
Laekker
https://tabelog.com/tw/tokyo/A1303/A130303/13243988/
代官山車站 / 麵包, 西式甜點
無
-
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.78
Ren Shan
https://tabelog.com/tw/tokyo/A1316/A131602/13190771/
白金高輪車站 / 中國菜
各地流傳的鄉村料理和傳承下來的家庭料理。在日本重現中國各地的味道
-
晚間價錢: JPY 8,000～JPY 9,999 午間價錢: -
------------------------------
3.78
Asakusa Sanboa
https://tabelog.com/tw/tokyo/A1311/A131102/13123270/
淺草車站 / 酒吧
無
星期三
晚間價錢: JPY 3,000～JPY 3,999 午間價錢: -
------------------------------
3.78
Romantico
https://tabelog.com/tw/tokyo/A1316/A131602/13021521/
白金台車站 / 義大利料理
無
-
晚間價錢: JPY 10,000～JPY 14,999 午間價錢: -
------------------------------
3.78
La Strada
https://tabelog.com/tw/tokyo/A1319/A131903/13141774/
中野坂上車站 / 蕎麥麵
細打、粗打、平打。具有不同個性的蕎麥風味的3種蕎麥
星期一、星期日
晚間價錢: JPY 8,000～JPY 9,999 午間價錢: -
------------------------------
3.78
Soba Ya Tsukigokoro
https://tabelog.com/tw/tokyo/A1317/A131701/13096494/
祐天寺車站 / 蕎麥麵, 日本料理
無
星期二、星期三
晚間價錢: JPY 6,000～JPY 7,999 午間價錢: JPY 4,000～JPY 4,999
------------------------------
3.78
Ginza Inaba
https://tabelog.com/tw/tokyo/A1301/A130101/13259495/
東銀座車站 / 日本料理
盡享銀座稻葉不拘泥於任何事物的“融通無礙”的世界觀。與料理一起感受季節的變遷!
-
晚間價錢: JPY 30,000～JPY 39,999 午間價錢: JPY 8,000～JPY 9,999
------------------------------
3.78
Pepe Rosso
https://tabelog.com/tw/tokyo/A1318/A131801/13243643/
池之上車站 / 義大利料理, 洋酒吧, 餐飲酒館
【傳統與創新的融合】在池上享受不斷演變的当地美食與葡萄酒的搭配。可當天預訂
星期一
晚間價錢: JPY 10,000～JPY 14,999 午間價錢: JPY 8,000～JPY 9,999
------------------------------
3.78
Cignale ENOTECA
https://tabelog.com/tw/tokyo/A1318/A131801/13189915/
神泉車站 / 義大利料理
無
-
晚間價錢: JPY 30,000～JPY 39,999 午間價錢: -
------------------------------
3.78
Kasai
https://tabelog.com/tw/tokyo/A1317/A131702/13242439/
都立大學車站 / 義大利料理
享受正宗的套餐和葡萄酒，充分發揮食材的魅力◎安靜住宅區的義大利菜小餐廳
星期三
晚間價錢: JPY 15,000～JPY 19,999 午間價錢: -
------------------------------
3.78
Sushi Fujinaga
https://tabelog.com/tw/tokyo/A1307/A130702/13265370/
麻布十番車站 / 壽司
無
-
晚間價錢: JPY 60,000～JPY 79,999 午間價錢: -
------------------------------
3.78
Crony
https://tabelog.com/tw/tokyo/A1314/A131401/13256097/
赤羽橋車站 / 法式料理
無
-
晚間價錢: JPY 20,000～JPY 29,999 午間價錢: -
------------------------------
頁數: 33
3.78
Ten Yokota
https://tabelog.com/tw/tokyo/A1307/A130702/13258792/
麻布十番車站 / 天婦羅, 日本料理
無
星期三
晚間價錢: JPY 15,000～JPY 19,999 午間價錢: -
------------------------------
3.78
Jfree
https://tabelog.com/tw/tokyo/A1309/A130905/13279528/
飯田橋車站 / 法式料理, 洋酒吧
享受由法式料理三星廚師打造的充滿日本風味的“現代法式料理”
星期一、星期日
晚間價錢: JPY 20,000～JPY 29,999 午間價錢: -
------------------------------
3.78
Oryori Tsuji
https://tabelog.com/tw/tokyo/A1307/A130702/13209899/
麻布十番車站 / 日本料理
在莊重的空間中享用體現四個季節的日本料理套餐【全國配送。我們接受節日預訂]
星期日、節假日
晚間價錢: JPY 20,000～JPY 29,999 午間價錢: JPY 10,000～JPY 14,999
------------------------------
3.78
A New Shohei Shimono
https://tabelog.com/tw/tokyo/A1307/A130703/13238000/
廣尾車站 / 創新, 創作料理, 法式料理
無
-
晚間價錢: JPY 20,000～JPY 29,999 午間價錢: -
------------------------------
3.78
Tanimoto
https://tabelog.com/tw/tokyo/A1309/A130905/13288233/
飯田橋車站 / 日本料理
無
星期日
晚間價錢: JPY 30,000～JPY 39,999 午間價錢: JPY 30,000～JPY 39,999
------------------------------
3.78
Sakuragi
https://tabelog.com/tw/tokyo/A1313/A131301/13275135/
築地車站 / 日本料理
距離築地站 5 分鐘 ◆ 在每月的套餐中，享受經驗豐富的鑑賞家精心挑選的豪華時令食材。即使是在重要的紀念日
-
晚間價錢: JPY 20,000～JPY 29,999 午間價錢: -
------------------------------
3.77
Rokurinsha
https://tabelog.com/tw/tokyo/A1302/A130201/13093047/
東京車站 / 沾麵, 拉麵
無
-
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
Fuuunji Shinjuku Hon Ten
https://tabelog.com/tw/tokyo/A1304/A130401/13044091/
南新宿車站 / 拉麵, 沾麵
無
-
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
Tsukemen Gonokami Seisakujo
https://tabelog.com/tw/tokyo/A1304/A130401/13120708/
新宿三丁目車站 / 沾麵
無
-
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Menya Hyottoko Kotsukan Ten
https://tabelog.com/tw/tokyo/A1301/A130102/13046637/
有樂町車站 / 拉麵
無
星期日、節假日
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
Mugi to Olive Ginza Hon Ten
https://tabelog.com/tw/tokyo/A1301/A130101/13164932/
東銀座車站 / 拉麵, 沾麵
無
星期三
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Chuka Menten Kiraku
https://tabelog.com/tw/tokyo/A1303/A130301/13001705/
神泉車站 / 拉麵, 餃子, 中國菜
無
星期三
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
Ramen Jiro Mita Honten
https://tabelog.com/tw/tokyo/A1314/A131402/13006051/
三田車站 / 拉麵
無
星期日
晚間價錢: - 午間價錢: ～JPY 999
------------------------------
3.77
Mendokoro Honda Akihabara Honten
https://tabelog.com/tw/tokyo/A1310/A131001/13246285/
秋葉原車站 / 拉麵, 沾麵, 乾擔擔麵
無
星期三
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Gavial
https://tabelog.com/tw/tokyo/A1310/A131003/13000358/
神保町車站 / 咖喱
無
星期二
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Tsukemen Kinryu
https://tabelog.com/tw/tokyo/A1310/A131002/13259807/
小川町車站 / 拉麵, 沾麵
用粘稠的鰹魚海帶湯汁浸泡過的面條和清爽的海鮮湯汁吃的新感覺的蘸汁面!
-
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Soranoiro ARTISAN NOODLES
https://tabelog.com/tw/tokyo/A1308/A130803/13126816/
麴町車站 / 拉麵
無
星期六、星期日
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Yakumo
https://tabelog.com/tw/tokyo/A1317/A131705/13204333/
池尻大橋車站 / 拉麵, 沾麵
無
星期二
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Menya Hulu-lu
https://tabelog.com/tw/tokyo/A1305/A130501/13136428/
池袋車站 / 拉麵
面屋Hulu-lu
星期二
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
La Brianza
https://tabelog.com/tw/tokyo/A1307/A130701/13194346/
六本木車站 / 義大利料理, 義大利麵, 肉類料理
在六本木新城的寧靜空間中享用義大利菜。非常適合特殊場合和團體聚會。
-
晚間價錢: JPY 10,000～JPY 14,999 午間價錢: JPY 4,000～JPY 4,999
------------------------------
頁數: 34
3.77
Kyu Yamu Tei Shimokita So
https://tabelog.com/tw/tokyo/A1318/A131802/13211142/
下北澤車站 / 咖喱, 印度咖哩
無
星期二
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Mendokoro Bigiya Gakugei Daigaku Honten
https://tabelog.com/tw/tokyo/A1317/A131702/13093976/
學藝大學車站 / 拉麵, 沾麵
無
-
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: ～JPY 999
------------------------------
3.77
3 Chome no Curry Ya San
https://tabelog.com/tw/tokyo/A1302/A130202/13025962/
寶町車站 / 咖喱
無
星期日
晚間價錢: JPY 2,000～JPY 2,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Junteuchi Men to Mirai
https://tabelog.com/tw/tokyo/A1318/A131802/13221486/
下北澤車站 / 拉麵
無
-
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
L'Atelier du pain
https://tabelog.com/tw/tokyo/A1307/A130701/13147689/
六本木車站 / 麵包, 咖啡店
無
-
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
Patisserie Satsuki
https://tabelog.com/tw/tokyo/A1308/A130803/13000178/
麴町車站 / 蛋糕, 麵包
無
-
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
Le Pan de Joël Robuchon Nyuman Shinjukuten
https://tabelog.com/tw/tokyo/A1304/A130401/13193559/
新宿車站 / 麵包
無
-
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
Fruit Parlour Goto
https://tabelog.com/tw/tokyo/A1311/A131102/13095672/
淺草車站 / 水果聖代, 咖啡店, 剉冰
無
星期三、星期四
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
noix de beurre Shinjuku Isetan Ten
https://tabelog.com/tw/tokyo/A1304/A130401/13124571/
新宿三丁目車站 / 蛋糕, 巧克力
無
-
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
RAMEN CiQUE
https://tabelog.com/tw/tokyo/A1319/A131905/13048520/
南阿佐谷車站 / 拉麵
無
星期一
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
LA BONNE TABLE
https://tabelog.com/tw/tokyo/A1302/A130202/13166325/
三越前車站 / 法式料理, 法式小酒館, 洋酒吧
新菜單陸續登場！
星期一
晚間價錢: JPY 15,000～JPY 19,999 午間價錢: JPY 8,000～JPY 9,999
------------------------------
3.77
Tonkatsu Enraku
https://tabelog.com/tw/tokyo/A1317/A131714/13034183/
池上車站 / 炸豬排, 炸豬排蓋飯
無
星期一、星期日
晚間價錢: JPY 2,000～JPY 2,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Kameido Niboshi Chuka Soba Tsukihi
https://tabelog.com/tw/tokyo/A1312/A131202/13217695/
龜戶車站 / 拉麵
無
-
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
tecona bagel works
https://tabelog.com/tw/tokyo/A1318/A131810/13061492/
代代木公園車站 / 貝果, 麵包, 三明治
無
-
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
Spicy Curry House Hangetsu
https://tabelog.com/tw/tokyo/A1304/A130401/13211678/
西武新宿車站 / 咖喱, 印度咖哩
無
-
晚間價錢: - 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Seijuken
https://tabelog.com/tw/tokyo/A1302/A130204/13213772/
小傳馬町車站 / 日式點心, 銅鑼燒
無
星期六、星期日、節假日
晚間價錢: - 午間價錢: ～JPY 999
------------------------------
3.77
Criollo Nakameguro Ten
https://tabelog.com/tw/tokyo/A1317/A131701/13077927/
中目黑車站 / 蛋糕, 巧克力, 馬卡龍
無
-
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: -
------------------------------
3.77
Katane Bakery
https://tabelog.com/tw/tokyo/A1318/A131811/13020931/
代代木上原車站 / 麵包, 三明治
無
星期一
晚間價錢: ～JPY 999 午間價錢: -
------------------------------
3.77
Fru-Full Akasaka Ten
https://tabelog.com/tw/tokyo/A1308/A130801/13155288/
赤坂車站 / 水果聖代, 鬆餅, 咖啡店
赤坂站5分鐘可以品嘗到用銅板烤制的薄煎餅和時令水果，令人懷唸的新時尚酒吧
星期一
晚間價錢: JPY 3,000～JPY 3,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
CHANTOYA COCONUT CURRY
https://tabelog.com/tw/tokyo/A1310/A131002/13131134/
新御茶之水車站 / 咖喱
無
-
晚間價錢: - 午間價錢: JPY 1,000～JPY 1,999
------------------------------
頁數: 35
3.77
Tachibana
https://tabelog.com/tw/tokyo/A1301/A130103/13022189/
新橋車站 / 日式點心
無
星期日、節假日
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Kamodashi Chuka Soba Menya yoshiki
https://tabelog.com/tw/tokyo/A1312/A131204/13242295/
新小岩車站 / 拉麵, 沾麵
Menya Itto 的 Abe Yoshiki 終於獨立了。一定要嚐嚐「鴨」拉麵
星期四
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Iriya Kishimojin Monzen no Daya
https://tabelog.com/tw/tokyo/A1311/A131104/13152282/
入谷車站 / 鰻魚, 海鮮, 日本料理
創業1868年的廚師會直營店!敬請品嘗鰻魚料理人總本家的當家大師魅力十足的“匠之技”!
星期一
晚間價錢: JPY 10,000～JPY 14,999 午間價錢: JPY 8,000～JPY 9,999
------------------------------
3.77
Levain Tomigaya Ten
https://tabelog.com/tw/tokyo/A1318/A131810/13001841/
代代木八幡車站 / 麵包
無
星期一
晚間價錢: - 午間價錢: ～JPY 999
------------------------------
3.77
LA BOUTIQUE de Joel Robushon Ebisu Garden Place Ten
https://tabelog.com/tw/tokyo/A1303/A130302/13014064/
惠比壽車站 / 麵包, 蛋糕, 三明治
無
-
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Chimoto
https://tabelog.com/tw/tokyo/A1317/A131702/13003218/
都立大學車站 / 日式點心, 日式甜點店, 剉冰
無
星期三、星期四
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: ～JPY 999
------------------------------
3.77
PRETTY PORK FACTORY
https://tabelog.com/tw/tokyo/A1304/A130401/13254601/
西武新宿車站 / 豬肉涮涮鍋, 韓國料理
PRETTY PORK FACTORY&KATSU Prepo 4/17將在原宿Harakado開業
-
晚間價錢: JPY 8,000～JPY 9,999 午間價錢: JPY 3,000～JPY 3,999
------------------------------
3.77
Gin Cock
https://tabelog.com/tw/tokyo/A1310/A131002/13102075/
淡路町車站 / 咖喱, 印度咖哩
無
星期六、星期日、節假日
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Umemura
https://tabelog.com/tw/tokyo/A1311/A131102/13008698/
淺草車站 / 日式甜點店, 剉冰, 日式點心
無
星期日
晚間價錢: ～JPY 999 午間價錢: ～JPY 999
------------------------------
3.77
Fiorentina Pastry Boutique
https://tabelog.com/tw/tokyo/A1307/A130701/13060521/
六本木車站 / 蛋糕, 麵包, 巧克力
連飯店女服務生都覺得美麗的各種甜點
-
晚間價錢: JPY 1,000～JPY 1,999 午間價錢: JPY 1,000～JPY 1,999
------------------------------
3.77
Patisserie l’abricotier
https://tabelog.com/tw/tokyo/A1319/A131904/13100828/
高圓寺車站 / 蛋糕, 咖啡店
無
星期一、星期二
晚間價錢: ～JPY 999 午間價錢: JPY 1,000～JPY 1,999

In [4]:
practice = pd.DataFrame([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
], columns = ["a", "b", "c"], index = ["c", "d", "e"])
practice

   a  b  c
c  1  2  3
d  4  5  6
e  7  8  9

In [6]:
# 取行: 字典
practice["a"]
practice[["a", "c"]]

   a  c
c  1  3
d  4  6
e  7  9

In [7]:
# pandas主要型態分兩種
# 1. DataFrame: 表格型態, 有行有列 (2D)
# 2. Series: list型態, 單行單列 (1D)
print(type(practice["a"]))
print(type(practice[["a", "c"]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [11]:
# 取列 1. 看它實際第幾列(iloc): list, 把0...2當key  2. 看列標籤(loc): 字典, 列標籤當key
# 專屬值
practice.loc["d"]
practice.iloc[0:2]

   a  b  c
c  1  2  3
d  4  5  6

In [12]:
# 過濾(filter)原理: 把跟妳列的筆數一樣多的True False帶給她[]
# 對到True的就會留下, 對到False的就會丟掉
fil = [True, False, True]
practice[fil]

   a  b  c
c  1  2  3
e  7  8  9

In [23]:
df["rating"] = df["rating"].astype("float")
# fil = df["rating"] >= 4.0
# df[fil]
# 你可以作條件組合 and -> &, or -> |
fil = (df["rating"] <= 4.1) & (df["rating"] >= 3.8)
df[fil]

,name(en),url,area,intro,rating
0,Nihonbashi Kakigaracho Sugita,https://tabelog.com/tw/tokyo/A1302/A130204/130...,水天宮前車站 / 壽司,將江戶前的精髓傳承至今的壽司。持續進化的職人技藝和細衹周到，極具魅力的正統派江戶前壽司。,4.67
1,Shimbashi Hoshino,https://tabelog.com/tw/tokyo/A1314/A131401/131...,御成門車站 / 日本料理,將食材的美味發揮到極致的日本料理大師。,4.63
2,Higashiazabu Amamoto,https://tabelog.com/tw/tokyo/A1314/A131401/131...,赤羽橋車站 / 壽司,繼承了名店的靈魂，將極品魚的精湛技藝發揮到極衹的現代江戶前壽司的未來,4.61
3,Aka,https://tabelog.com/tw/tokyo/A1302/A130202/132...,三越前車站 / 西班牙料理,精緻的西班牙菜，閃耀著日本的美感和東主廚的獨創性。,4.61
4,Sushi Arai,https://tabelog.com/tw/tokyo/A1301/A130101/131...,銀座車站 / 壽司,在擔任久兵衛和壽司師傅后，他在 33 歲時獨立。 堅持「握壽司」的新一代銀座壽司,4.59
...,...,...,...,...,...
201,SATO Brian Hon Ten,https://tabelog.com/tw/tokyo/A1319/A131905/131...,阿佐谷車站 / 燒肉,目前接受2月份的預約▶請從官方網站進行預約。,4.00
202,Tomidokoro,https://tabelog.com/tw/tokyo/A1314/A131401/132...,御成門車站 / 壽司,無,4.00
203,L'Atelier à Ma Façon,https://tabelog.com/tw/tokyo/A1317/A131715/132...,"上野毛車站 / 甜點, 咖啡店",無,4.00
204,Kalpasi,https://tabelog.com/tw/tokyo/A1318/A131813/132...,"千歲船橋車站 / 印度咖哩, 尼泊爾料理, 斯里蘭卡料理",每週一道套餐咖哩，讓香料烹飪愛好者垂涎欲滴。,4.00
205,Ara Ki,https://tabelog.com/tw/tokyo/A1308/A130801/132...,赤坂車站 / 壽司,無,4.00

In [39]:
table = []
for h in df["holiday"]:
    data = {
        "星期一":True,
        "星期二":True,
        "星期三":True,
        "星期四":True,
        "星期五":True,
        "星期六":True,
        "星期日":True,
    }
    check = data.keys()
    for c in check:
        if c in h:
            data[c] = False
    table.append(data)
df2 = pd.DataFrame(table)
total = pd.concat([df, df2], axis = 1)
# 過濾
fil = (total["星期日"] == True) & (total["rating"].astype("float") >=3.7)
total[fil]

,name(en),url,area,intro,rating,holiday,星期一,星期二,星期三,星期四,星期五,星期六,星期日
0,Nihonbashi Kakigaracho Sugita,https://tabelog.com/tw/tokyo/A1302/A130204/130...,水天宮前車站 / 壽司,將江戶前的精髓傳承至今的壽司。持續進化的職人技藝和細衹周到，極具魅力的正統派江戶前壽司。,4.67,-,True,True,True,True,True,True,True
3,Aka,https://tabelog.com/tw/tokyo/A1302/A130202/132...,三越前車站 / 西班牙料理,精緻的西班牙菜，閃耀著日本的美感和東主廚的獨創性。,4.61,-,True,True,True,True,True,True,True
4,Sushi Arai,https://tabelog.com/tw/tokyo/A1301/A130101/131...,銀座車站 / 壽司,在擔任久兵衛和壽司師傅后，他在 33 歲時獨立。 堅持「握壽司」的新一代銀座壽司,4.59,星期三,True,True,False,True,True,True,True
7,Ao,https://tabelog.com/tw/tokyo/A1307/A130701/132...,"六本木車站 / 創新, 法式料理",無,4.57,-,True,True,True,True,True,True,True
8,PELLEGRINO,https://tabelog.com/tw/tokyo/A1303/A130302/130...,廣尾車站 / 義大利料理,想最大限度地傳達食材的味道、香味、時令,4.57,-,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1193,Hasegawa,https://tabelog.com/tw/tokyo/A1312/A131201/130...,兩國車站 / 炸豬排,無,3.72,-,True,True,True,True,True,True,True
1194,Zopf Curry Pan Senmon Ten Gransta Ten,https://tabelog.com/tw/tokyo/A1302/A130201/132...,"東京車站 / 麵包, 咖喱",無,3.72,-,True,True,True,True,True,True,True
1195,Ramen Jiro Meguro Ten,https://tabelog.com/tw/tokyo/A1316/A131601/130...,目黑車站 / 拉麵,無,3.72,-,True,True,True,True,True,True,True
1197,Dame na Rinjin Ningyocho Ten,https://tabelog.com/tw/tokyo/A1302/A130204/132...,"人形町車站 / 拉麵, 油麵/拌麵, 沾麵",人形町站旁邊！ ◆享受嚴選食材製作的精緻拉麵和土鍋飯♪外帶也可以◎,3.72,-,True,True,True,True,True,True,True
1198,DANDELION CHOCOLATE Fakutori Ando Kafe Kuramae,https://tabelog.com/tw/tokyo/A1311/A131103/131...,"藏前車站 / 巧克力, 咖啡店, 西式甜點",無,3.72,-,True,True,True,True,True,True,True

In [38]:
# Series.apply(轉換方式)
# 原有值 -> 轉換方式 -> 新值
# 轉換方式就是一個函式 不加小括號
df["rating"] = df["rating"].astype("float")
df["rating"].apply(round)

0       5
1       5
2       5
3       5
4       5
       ..
1195    4
1196    4
1197    4
1198    4
1199    4
Name: rating, Length: 1200, dtype: int64

In [35]:
# 函式是形態(?????)
# 以前: 我跟妳說每個功能都要加小括號, 就算沒帶入參數也要加
# Everything is an object: 每個東西都是有形態的, 每個形態都有這個形態可以做的操作
# list 操作:[0] [-1]  dict 操作: [key]
# round(4.2)???
# round是一個形態 (4.2)是這個形態的操作
# round是步驟集合形態  (4.2)才是真的把這個步驟執行完得到節果
# 刷牙步驟        開始刷
# 函式形態: 還沒被打開的錦囊
# 加小括號: 把錦囊打開, 執行並得到結果
b = round
b(4.5)

import math
def func(state):
    if state == 0:
        return math.gcd
    else:
        return math.lcm
func(1)(6, 9)

18